version: '3'

services:
  ecourses-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - ecourses

    
  ecourses-api:
    image: ecourses/api
    restart: unless-stopped
    build: .
    environment:
      - ConnectionStrings:eCourses=Server=ecourses-sql,1433;Database=eCoursesDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      -  63679:5000
    networks:
      - ecourses    
    links:
      - ecourses-sql
    depends_on:
      - ecourses-sql
      
networks:
  ecourses:
    driver: bridge

        